# Generated by Django 2.2.4 on 2019-11-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_2Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums_title', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
